import Head from "next/head";
import { Layout } from "@/components/Layout";
import { Hero } from "@/components/Hero";
import { Box, Container, Flex } from "@chakra-ui/react";
import { HomeBrands } from "@/components/HomeBrands";
import { VideoModal } from "@/components/VideoModal";
import { InfoCardList } from "@/components/InfocardList";
import { InfocardTab } from "@/components/InfocardTab";
import { data } from "@/utils/data";
import { InfocardSlider } from "@/components/InfocardSlider";

export default function Home() {
  const { home } = data;
  return (
    <Box bgGradient={"linear(to-r, white, #6a5fe53b)"}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout>
        <Box maxW={["", "container.xl"]} mx="auto" p={[0, 4]} my={16}>
          <Hero />
        </Box>

        <Container maxW={"container.xl"}>
          <HomeBrands />
        </Container>

        <Container maxW={"container.xl"} my={16}>
          <Flex justify={"center"}>
            <VideoModal />
          </Flex>
        </Container>

        <Container maxW={"container.xl"} my={16}>
          <InfoCardList />
        </Container>

        <Container maxW={"container.xl"} my={16}>
          <InfocardTab data={home.infoCardTab} />
        </Container>

        <InfocardSlider data={home.infoCardSlider} />
      </Layout>
    </Box>
  );
}
